spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/eclaims
    username: eclaims
    password: eclaims123
    driver-class-name: org.postgresql.Driver

storage:
  minio:
    endpoint: http://localhost:9000

mail:
  smtp:
    host: localhost
    port: 1025

