package com.nagarro.eclaims.notification.enums;

public enum NotificationEventType {
    CLAIM_SUBMITTED,
    CLAIM_CASE_ASSIGNED,
    CLAIM_SURVEYOR_ASSIGNED,
    CLAIM_SURVEY_COMPLETED,
    CLAIM_ADJUSTOR_ASSIGNED,
    CLAIM_APPROVED,
    CLAIM_REJECTED,
    CLAIM_WORKSHOP_ASSIGNED,
    CLAIM_REPAIR_STARTED,
    CLAIM_REPAIR_COMPLETED,
    CLAIM_PAYMENT_INITIATED,
    CLAIM_PAYMENT_COMPLETED,
    CLAIM_CLOSED
}

